### PR TITLE
Add support for bpkg package manager

### PR DESCRIPTION
**Pull request by Akagi201**
Add support for [bpkg](https://github.com/bpkg/bpkg).

bpkg is a lightweight bash package manager.

### CODE REVIEW

**Comment by aurora** [comment]
Thanks' very much!!

**Comment by duzun** [comment]
Any plans to actually add `rmate` to `bpkg` ?

**Comment by aurora** [comment]
@duzun Yes, i already opened a PR at bpkg for it: https://github.com/bpkg/bpkg.github.io/pull/39 ... hopefully it get's accepted, soon.

**Comment by aurora** [comment]
@duzun and now it's merged :-) http://www.bpkg.io/pkg/rmate

**Comment by duzun** [comment]
@aurora cool!

**Pull request merged**
