### PR TITLE
Implemented ability to open a folder

### PR DESCRIPTION
**Pull request by KES777**
https://github.com/henrikpersson/rsub/issues/37

### CODE REVIEW

**Comment by aurora** [comment]
Thanks for your patch! I've always rejected this feature in the past because i think you can easily do this already in combination with other commands like `find`. Anyway ... i leave this open and play around with it ... maybe i'll change my mind! :wink:

**Comment by KES777** [comment]
oh, you can replace my code by line using find =). I use linux under 10 years and I do not know how to use find. I need to google, read some article ... ((( it is too hard vs:  rsub dir/

**Comment by ginolon** [comment]
This is how to open many files in a folder in many tabs in SublimeText. But how to open a folder, like `subl .` command?

**Comment by KES777** [comment]
@ginolon : yes, that is interesting feature. but not supported yet. There is [bounty](https://www.bountysource.com/issues/3174245-ability-to-open-a-folder)

**Comment by ickc** [comment]
This line is not safe: `for dir in `ls $filepath` ; do`. e.g. use `find ... -exec` or `find ... -print0 | xargs -0 ...` instead.

**Comment by aurora** [comment]
I am closing this pull request, as there's a merge-conflict currently anyway. Also i think the functionality should be implemented using features of the current rmate version (using the open_file function rather than spawning additional rmate processes). I have some ideas regarding this and am working on an own patch to support this now.

**Pull request closed without merging**
