### PR TITLE
support multi files opening

### PR DESCRIPTION
**Pull request by randy3k**
As in the official rmate, it supports opening multiple files. `rmate foo.txt bar.txt baz.txt`.
I basically wrap the original code in the function `open_file` and do a for loop

``` bash
for file in "${filepaths[@]}"; do
    open_file "$file"
done
```

### CODE REVIEW

**Comment by randy3k** [comment]
Tested in textmate and (atom](https://atom.io/packages/remote-atom). And apparently, [sublime](https://github.com/henrikpersson/rsub) doesn't support it.

**Comment by randy3k** [comment]
Ops....each file should have its corresponding `--line`, `--name` and `--type` arguments.

**Comment by randy3k** [comment]
Tested in textmate and [atom](https://atom.io/packages/remote-atom). And apparently, [sublime](https://github.com/henrikpersson/rsub) doesn't support it.

**Comment by aurora** [comment]
@randy3k hey, i have to take a further look at this, because it seems to be quite a big change. but due to health reasons it'll take some weeks until i can look into it ...

**Comment by randy3k** [comment]
Take your time. I totally understand it.

**Comment by tiennou** [comment]
I've been using that version a few times on various Linux-based server, and it works quite well.

**Comment by randy3k** [comment]
@aurora 

this has been sitting here for 1.5 year, how do you think about it?

**Comment by aurora** [comment]
@randy3k i am really sorry about the long delay, i am going to merge it. Thanks very much for your work and your patience on this :-)!

**Pull request merged**
